config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :post_images, only: [:new, :create, :index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    belongs_to :user
    attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   has_many :post_images, dependent: :destroy
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    post_images_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
   @post_image = PostImage.new
  end

  def create
   @post_image = PostImage.new(post_image_params)
   @post_image.user_id = current_user.id
   @post_image.save
   redirect_to post_images_path
  end

  def index
   @post_images = PostImage.all
  end

  def show
   @post_image = PostImage.find(params[:id])
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  
  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/homes/top.html.erb
<h1>トップページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    
    <li>
    <%= link_to '投稿フォーム', new_post_image_path %>
    </li>
    <li>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    </li>
    <% else %>
    <li>
    <%= link_to "新規登録", new_user_registration_path %>
    </li>
    <li>
    <%= link_to "ログイン", new_user_session_path %>
    </li>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/post_images/index.html.erb
<% @post_images.each do |post_image| %>
<div>
  <%= link_to post_image_path(post_image.id) do %>
  <%= attachment_image_tag post_image, :image %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag('sample-author1.jpg') %></p>
  <p>ショップ名：<%= post_image.shop_name %></p>
  <p>説明：<%= post_image.caption %></p>
  <p>ユーザーネーム：<%= post_image.user.name %></p>
</div>
<% end %>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @post_image, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

app/views/post_images/show.html.erb
<div>
  <%= attachment_image_tag @post_image, :image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == current_user %>
  <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
</div>